site_name: Ultimate Guide to BOSH
pages:
  - Guide:
    - Welcome: index.md
    - Introduction: introduction.md
    - Why BOSH?: why-bosh.md
    - Deployments: deployments.md
    - Instances: instances.md
    - Deployment Manifests: deployment-manifests-part-1.md
    - Networking: networking.md
    - Disks: disks.md
    - Cloud Config Updates: cloud-config-updates.md
    - Deployment Updates: deployment-updates.md
    - Releases: releases.md
    - Properties: properties.md
    - Stemcells: stemcells.md
    - Complete Deployment Manifest: complete-deployment-manifest.md
    - Service Discovery: service-discovery.md
    - Targeting BOSH Environments and Deployments: targeting-bosh-envs.md
  - Complete Tutorials:
    - bosh-lite on VirtualBox: tutorials/bosh-lite-virtualbox.md
  - Spread the Word:
    - Meetups: spread-the-word/meetups.md
  - Ask For Help:
    - Suggestions: ask-for-help/suggestions.md

theme:
  name: 'material'
  custom_dir: 'theme-overrides'
  palette:
    primary: 'orange'
    accent: 'amber'
  feature:
    tabs: true

  logo: 'images/favicon/favicon-64.png'

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc(permalink=true)

repo_name: 'help fix the book'
repo_url: 'https://github.com/starkandwayne/ultimate-guide-to-bosh'
edit_uri: edit/master/docs/
extra_css: [print.css]
google_analytics: ['UA-50822525-5', 'utlimateguidetobosh.com']